apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discovery-server
  name: discovery-server
  namespace: carmarketplace-$ENVIRONMENT
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: geekymon2/cm-discovery-server:latest
        env:
        - name: ENVIRONMENT
          value: $ENVIRONMENT
        - name: ARTIFACT_NAME
          value: "discovery-server"
        - name: SPRING_PROFILES_ACTIVE
          value: $ENVIRONMENT
        - name: TZ
          value: "Australia/Sydney"
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
          - containerPort: 8761