apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: carmarketplace-ci
spec:
  selector:
    app: discovery-server  
  ports:
    - name: http
      protocol: TCP
      port: 8761
      targetPort: 8761