apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: carmarketplace-$ENVIRONMENT
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: $UI_PORT
