apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui
  name: ui
  namespace: carmarketplace-$ENVIRONMENT
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: cm-ui
          image: geekymon2/cm-ui:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: ENVIRONMENT
              value: "$ENVIRONMENT"
            - name: TZ
              value: "Australia/Sydney"
            - name: SPRING_PROFILES_ACTIVE
              value: "$ENVIRONMENT"
            - name: UI_HOST
              value: "$UI_HOST"
            - name: UI_PORT
              value: "$UI_PORT"
          command: ["/bin/sh", "-c", "/app/generate-config.sh"]